spring.application.name=FileReaderApplication


management.tracing.sampling.probability=1
management.tracing.export.zipkin.endpoint=18.60.39.200/api/v2/spans
management.tracing.enabled=true
management.observations.http.server.requests.enabled=true
management.endpoints.web.exposure.include=*

logging.pattern.level=%5p [${spring.application.name:},traceId=%X{traceId},spanId=%X{spanId}]